on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            env: {}

          - os: ubuntu-latest
            env:
              PLATFORM: mingw32
              DEFAULT_HOMEDIR: .

          - os: macos-latest
            env: {}

    steps:
      - uses: actions/checkout@v2

      - name: setup
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt install -yy mingw-w64 libgl1-mesa-dev libsdl2-dev libfreetype6-dev libxxf86vm-dev

      - name: build
        run: |
          make all
          make all ARCHIVE=1 -j1
          cd build
          for file in *.zip; do
            bname=$(basename "$file" .zip)
            bname=${bname/mingw32-/windows}
            bname=${bname/darwin-universal/macOS}
            bname=${bname/linux-/linux}
            bname=${bname/x86_64/64}
            bname=${bname/x86/32}
            mv "$file" "ioq3urt-m9-${bname}-${version}.zip"
          done
        env: ${{ matrix.env }}

      - uses: actions/upload-artifact@v2
        with:
          path: build/*.zip
